### ISSUE TITLE
Wrong/Unregistered Mobile Number (ensure there's no +91 or 0 in the beginning)

### ISSUE THREAD

**Issue by gyandoo** [astravaganza/JC-dl#6]
keep getting this error even though my mobile number is registered, thanks

**Comment by swappyison** [comment]
@gyandoo you can try this:https://github.com/swappyison/JiocinemaDownloader

**Comment by gyandoo** [comment]
@swappyison thanks, any easier solution like this app [https://www.apkmirror.com/apk/rahul-verma/videoder/](https://www.apkmirror.com/apk/rahul-verma/videoder/ ) that used to work, I don't use chrome

**Comment by astravaganza** [comment]
This is apparently due to JC migrating to v4. I will try to update the endpoints soon.

**Comment by astravaganza** [comment]
fixed with https://github.com/astravaganza/JC-dl/commit/b8f36a723b0ea841f303f09e48cd2b7c6533921d
